### ISSUE TITLE
Handle DC Pickup Guardian

### ISSUE THREAD

**Issue by shmakes** [shmakes/hf-basic#131]
They need to not be on the flight manifest.

**Comment by shmakes** [comment]
If they are a DC Pickup, they wouldn't have a seat assignment so they could be filtered out of the list given to TSA. Or does this refer to having an indicator on the Flight Detail page or Flight Export to signify DC Pickup when assigning seats?

**Comment by shmakes** [comment]
Looking at changing this to a separate "NotFlying" flag for vets and guardians. That flag will be used to suppress the count on the flight assignment page and prevent seat assignment on the flight detail page. However bus assignment will still be allowed on the flight detail page and the counts will include the non-flying vets/guardians.

**Comment by PaulaNelson** [comment]
Sounds great!

Also, my "copy" function and auto-fill are not working. Any suggestions?

**Comment by shmakes** [comment]
Tasks:

- Add checkbox to vet and grd form
- when saving "nofly" set seat number to "NF"
- when nofly is active disable seat editing
- add to flight export
- adjust flight totals on assignment page
- indicate nofly on assignment page
- lock seat assignment for nofly on details page
- indicate nofly on details page
