### ISSUE TITLE
Please set LEVEL field to allow only one number

### ISSUE THREAD

**Issue by PaulaNelson** [shmakes/hf-basic#136]

**Comment by shmakes** [comment]
There is already a validation in place for that - it only allows a single digit of 1, 2, 3, 4, or 5.
I can not reproduce the issue with Chrome or Firefox.
Can you please provide more detail on where you saw this issue?

**Comment by PaulaNelson** [comment]
Hmmmm...I cant either now.  I never tried to enter more than one number.  I
thought Amy K and I has run into ranges when we were assigning seats.  You
can close this issue for now.  I copied Amy in - - we'll see if she
remembers what the issue was!​

Paula

On Wed, Nov 25, 2015 at 11:15 AM, Steve Schmechel <notifications@github.com>
wrote:

> There is already a validation in place for that - it only allows a single
> digit of 1, 2, 3, 4, or 5.
> I can not reproduce the issue with Chrome or Firefox.
> Can you please provide more detail on where you saw this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shmakes/hf-basic/issues/136#issuecomment-159677639>.
>



-- 
Paula Nelson
President
Stars and Stripes Honor Flight
262-305-6424

**Comment by PaulaNelson** [comment]
Sorry, don’t remember this one.

-Amy

**Comment by shmakes** [comment]
Could not reproduce the issue.
