### ISSUE TITLE
Allow 3:2 vet guardian ratio

### ISSUE THREAD

**Issue by 3354sstt** [shmakes/hf-basic#175]
We'll be doing 3:2 vet/guardian ratios starting in May

**Comment by shmakes** [comment]
My recommendation would be to group the 3 veterans then assign 1 veteran to
one guardian and 2 to the other Guardian.

BTW I don't recognize the user name 3354sstt. Could you please include your
name also?

**Comment by shmakes** [comment]
My recommendation would be to group the 3 veterans then assign 1 veteran to one guardian and 2 to the other Guardian. 

BTW I don't recognize the user name 3354sstt. Could you please include your name also?

**Comment by shmakes** [comment]
My thought is that we could add a new screen to quickly see who is associated with a veteran or guardian by showing their flight group and pairings together on a pop-up on the edit forms. We could also look at some display and/or ordering improvements to make the flight assignment and detail screens better.

**Comment by 3354sstt** [comment]
I think showing vet groupings and the guardians associated with the group would be a great start.

**Comment by shmakes** [comment]
Flight details page can now be sorted by flight group to bring associated veterans and guardians together in one place. We could still add a separate form for convenience, but maybe the priority could be a bit lower now? What do you think?

**Comment by shmakes** [comment]
Do we still need this ticket?

**Comment by shmakes** [comment]
Sorting on Flight Details page plus ability to add three veterans per guardian should cover the needs.
