### ISSUE TITLE
Add a checkbox

### ISSUE THREAD

**Issue by 3354sstt** [shmakes/hf-basic#197]
This request is for Marge

Please add a checkbox to "Guardian Fee paid by sponsor" or something that indicates this.

Jim K

**Comment by shmakes** [comment]
@3354sstt Was there ever any additional definition for this issue?

**Comment by 3354sstt** [comment]
I don’t remember. I’ll ask Marge what she was getting at

**Comment by 3354sstt** [comment]
You can scratch this … she doesn’t think it’s needed any longer
