### ISSUE TITLE
Database Sorting Issue

### ISSUE THREAD

**Issue by mstolaski** [shmakes/hf-basic#226]
From Marge Meyers on 8/31/2022:

At Guardian Training this morning, I ran into a bit of a problem when I went into "Flights" then "Other Flight Items".  I normally am able to alphabetize the guardians/veterans names--I click, and they go into alphabetical order according to last name.  This makes it quite easy, as you know, to check off "Training" and "Paid".  Today, when I clicked on it, it sorted according to first name, which really wasn't of much help and which meant that I had to go into each DB record to mark them as attending GT or make any changes.  I asked Steve Vasatko to try, and he got the same results.  I've been doing this a LONG time, so I figured something must have changed.

When you have time, could you check this out?  Thank you."
Marge Meyers

**Comment by shmakes** [comment]
This got messed up when I added some columns. I forgot to adjust the column sorting.
I fixed the issue on the Other form and on the Medical form.

**Comment by shmakes** [comment]
Anytime you change something on that form it should change the underlying
data.
If you're noticing things that are not being saved, please let me know.
