### ISSUE TITLE
Birth Dates one day off on Flight Guardian Check-in Edit Form

### ISSUE THREAD

**Issue by mstolaski** [shmakes/hf-basic#258]
At the Guardian Training event for the April 20, 2024 flight, it was determined that the DOB field on the Flight Guardian Check-in Edit Form was one day earlier than the actual database. Examples: Paula Nelson shows 4/18/1962 on the edit form, but 4/19/1962
 on the actual database record. Steve Schmechel shows 4/30/1968 on the edit form, but 5/1/1968 on the actual database record.

Wondering if it is a leap year issue?

Prior edit forms are showing similar discrepancies as well.

<img width="1402" alt="Steve Schmechel DB record" src="https://github.com/shmakes/hf-basic/assets/16273705/4d701624-6bc5-48df-b2f7-a6398798688a">
<img width="1385" alt="04202024 Final Guardian Check-in Edit Form" src="https://github.com/shmakes/hf-basic/assets/16273705/580afa9e-bce3-4fd5-b478-52fd781d4f0c">
<img width="1435" alt="Paula Nelson DB record" src="https://github.com/shmakes/hf-basic/assets/16273705/e121da83-7f13-4226-beac-34cb4964e1b4">

**Comment by shmakes** [comment]
@mstolaski This should be fixed now. 
Please verify on the test or production database.

**Comment by mstolaski** [comment]
Thanks, Steve!

I spot-checked some of the entries in production and they look good!
